version: 2

models:
  - name: bronze_customers
    description: "Details of customers."
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
      - name: company_name
        description: "Name of the company."
      - name: contact_name
        description: "Name of the primary contact."
      - name: contact_title
        description: "Title of the primary contact."
      - name: address
        description: "Address of the customer."
      - name: city
        description: "City of the customer."
      - name: region
        description: "Region of the customer."
      - name: postal_code
        description: "Postal code of the customer."
      - name: country
        description: "Country of the customer."
      - name: phone
        description: "Phone number of the customer."
      - name: fax
        description: "Fax number of the customer."

  - name: bronze_order_details
    description: "Details of orders."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
      - name: product_id
        description: "Identifier of the product."
      - name: unit_price
        description: "Price per unit of the product."
      - name: quantity
        description: "Quantity of the product ordered."
      - name: discount
        description: "Discount applied to the order."

  - name: bronze_orders
    description: "Contains orders placed by customers."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
      - name: customer_id
        description: "Identifier of the customer who placed the order."
      - name: employee_id
        description: "Identifier of the employee handling the order."
      - name: order_date
        description: "Date the order was placed."
      - name: required_date
        description: "Date the order is required."
      - name: shipped_date
        description: "Date the order was shipped."
      - name: ship_via
        description: "Shipping method."
      - name: freight
        description: "Freight cost."
      - name: ship_name
        description: "Name of the shipper."
      - name: ship_address
        description: "Shipping address."
      - name: ship_city
        description: "Shipping city."
      - name: ship_region
        description: "Shipping region."
      - name: ship_postal_code
        description: "Shipping postal code."
      - name: ship_country
        description: "Shipping country."

  - name: bronze_products
    description: "Details of products."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
      - name: product_name
        description: "Name of the product."
      - name: supplier_id
        description: "Identifier of the supplier."
      - name: category_id
        description: "Identifier of the product category."
      - name: quantity_per_unit
        description: "Quantity per unit of the product."
      - name: unit_price
        description: "Price per unit of the product."
      - name: units_in_stock
        description: "Quantity of units in stock."
      - name: units_on_order
        description: "Quantity of units on order."
      - name: reorder_level
        description: "Reorder level for the product."
      - name: discontinued
        description: "Indicates if the product is discontinued."

  - name: silver_orders  # Nome do modelo
    description: "Tabela de pedidos do estágio"  # Descrição do modelo
    columns:
      - name: order_id  # Nome da coluna
        description: "ID único do pedido"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
          - unique  # Teste para garantir que os valores na coluna sejam únicos
      - name: customer_id  # Nome da coluna
        description: "ID do cliente que fez o pedido"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
          - relationships:  # Teste para garantir a integridade referencial
              to: ref('silver_customers')  # Referência ao modelo relacionado
              field: customer_id  # Campo da coluna relacionada

  - name: silver_order_details  # Nome do modelo
    description: "Tabela de detalhes dos pedidos"  # Descrição do modelo
    columns:
      - name: order_id  # Nome da coluna
        description: "ID do pedido"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
      - name: product_id  # Nome da coluna
        description: "ID do produto"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
      - name: unit_price  # Nome da coluna
        description: "Preço unitário"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
      - name: quantity  # Nome da coluna
        description: "Quantidade"  # Descrição da coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos

  - name: silver_customers  # Nome do modelo
    description: "View de clientes em stg"  # Descrição do modelo
    tags: ['untagged']  # Etiquetas para categorizar o modelo
    meta:  # Metadados adicionais
      owner: postgres  # Proprietário do modelo
      type: view  # Tipo do modelo (tabela ou view)
      package: northwind  # Pacote ao qual o modelo pertence
      qualquer_coisa: teste  # Pacote ao qual o modelo pertence
      language: sql  # Linguagem usada para definir o modelo
      relation: postgres.public.raw_customers  # Relação específica no banco de dados
      access: protected  # Nível de acesso ao modelo
      version: '1.0'  # Versão do modelo
      contract: Enforced  # Especifica que o contrato de schema é aplicado
    columns:
      - name: customer_id  # Nome da coluna
        description: "ID único do cliente"  # Descrição da coluna
        type: integer  # Tipo de dado esperado para a coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos
          - unique  # Teste para garantir que os valores na coluna sejam únicos
      - name: company_name  # Nome da coluna
        description: "Nome da empresa"  # Descrição da coluna
        data_type: varchar  # Tipo de dado esperado para a coluna
        tests:
          - not_null  # Teste para garantir que a coluna não tenha valores nulos